keyboardbuilds/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('keyboards/', views.keyboards_index, name='keyboards'),
    path('keyboards/<int:keyboard_id>', views.keyboard_detail, name='detail'),
    path('keyboards/create/', views.KeyboardCreate.as_view(), name='keyboard_create'),
    path('keyboards/<int:pk>/update/', views.KeyboardUpdate.as_view(), name='keyboard_update'),
    path('keyboards/<int:pk>/delete/', views.KeyboardDelete.as_view(), name='keyboard_delete'),
    path('keyboards/<int:keyboard_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Keyboard(models.Model):
  name = models.CharField(max_length=100)
  keyboard = models.CharField(max_length=100)
  switch = models.CharField(max_length=100)
  keycaps = models.CharField(max_length=100)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('detail', kwargs={'keyboard_id': self.id})

class Photo(models.Model):
  url = models.CharField(max_length=200)
  keyboard = models.ForeignKey(Keyboard, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for keyboard_id: {self.keyboard_id} @{self.url}"



## FILLER DATA BELOW
# keyboards = [
#   Keyboard('budget friendly', 'g413', 'red', 'GMK Alpaca'),
#   Keyboard('TKL lovers dream', 'GMMK pro', 'black inks', 'ePBT keycaps'),
#   Keyboard('Out of the box banger', 'Razer Huntman', 'blue', 'Razer keycaps')
# ]

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
S3_BASE_URL = 'https://s3.amazonaws.com/'
BUCKET = 'keyboardbuilds-ds'
from .models import Keyboard, Photo


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def keyboards_index(request):
    keyboards = Keyboard.objects.all()
    return render(request, 'keyboards/index.html', { 'keyboards': keyboards })

@login_required
def keyboard_detail(request, keyboard_id):
    keyboard = Keyboard.objects.get(id=keyboard_id)
    return render(request, 'keyboards/detail.html', { 'keyboard': keyboard })

class KeyboardCreate(LoginRequiredMixin, CreateView):
    model = Keyboard
    fields = ['name', 'keyboard', 'switch', 'keycaps']
    success_url = '/keyboards/'
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class KeyboardUpdate(LoginRequiredMixin, UpdateView):
    model = Keyboard
    fields = ['name', 'keyboard', 'switch', 'keycaps']

class KeyboardDelete(LoginRequiredMixin, DeleteView):
    model = Keyboard
    success_url = '/keyboards/'

@login_required
def add_photo(request, keyboard_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, keyboard_id=keyboard_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', keyboard_id=keyboard_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

    <h1>Keyboard Builds About</h1> 
    <hr />
    <p>Search different keyboard builds!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Keyboard Builds</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
<body>
    <header class="navbar-fixed">
        <nav>
          <div class="nav-wrapper">
            <ul>
              <li>
                <a href="/" class="left brand-logo">&nbsp;&nbsp;Keyboard Build</a>
              </li>
            </ul>
            <ul class="right">
              <li><a href="{% url 'about' %}">About</a></li>
              <li><a href="{% url 'keyboards' %}">Keyboards</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'keyboard_create' %}">Add A Build</a></li>
              <li><a href="{% url 'logout' %}">Log Out</a></li>
              {% else %}
              <li><a href="{% url 'login' %}">Log In</a></li>
              <li><a href="{% url 'signup' %}">Sign Up</a></li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </header>
      <main class="container">{% block content %} {% endblock %}</main>
      <footer class="page-footer">
        <div class="right">
          All Rights Reserved, &copy; 2022 Keyboard Builds &nbsp;
        </div>
      </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Keyboard Builds Homepage!</h1>
<hr />
{% endblock %}

main_app/templates/keyboards/detail.html
{% extends 'base.html' %} {% block content %}

<h1> Details </h1>

<div class="card">
    <div class="card-content">
        <span class="card-title">{{ keyboard.name }}</span>
        <p>Keyboard: {{ keyboard.keyboard }}</p>
        <p>Switches: {{ keyboard.switch }}</p>
        <p>Keycaps: {{ keyboard.keycaps }}</p>
    </div>
    {% for photo in keyboard.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form
        action="{% url 'add_photo' keyboard.id %}"
        enctype="multipart/form-data"
        method="POST"
        class="card-panel"
    >
        {% csrf_token %}
        <input type="file" name="photo-file" />
        <br /><br />
        <input type="submit" class="btn" value="Upload Photo" />
    </form>
    <div class="card-action">
        <a href="{% url 'keyboard_update' keyboard.id %}">Edit</a>
        <a href="{% url 'keyboard_delete' keyboard.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/keyboards/index.html
{% extends 'base.html' %} {% block content %}

<h1>Keyboard List</h1>

{% for keyboard in keyboards %}
<div class="card">
  <a href="{% url 'detail' keyboard.id %}">
    <div class="card-content">
      <span class="card-title">{{ keyboard.name}}</span>
      <p>Keyboard: {{ keyboard.keyboard }}</p>
      <p>Switches: {{ keyboard.switch }}</p>
      <p>Keycaps: {{ keyboard.keycaps }}</p>
      {% for photo in keyboard.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
      {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
      {% endfor %}
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/main_app/keyboard_confirm_delete.html
{% extends 'base.html'%} {% block content %}
<h1>Delete Keyboard</h1>

<h4>
    Are you sure you want to Delete
    <span class="teal-text">{{object.name}}</span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn" />
    <a href="{% url 'detail' keyboard.id %}" class="btn">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/keyboard_form.html
{% extends 'base.html'%} {% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Keyboard</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn"/>
</form>

{% endblock %}